config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  
  resources :reservations

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end
	def show
		puts Article.find(params[:id]).inspect
		@article = Article.find(params[:id])
	end
	def create

		@article = Article.new(params.require(:article).permit(:title, :text))

		@article.save
		redirect_to @article
	end
	def index
		@articles = Article.all
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def new
	end
	def show
		puts Reservation.find(params[:id]).inspect
		@reservation = Reservation.find(params[:id])
	end
	def create

		@reservation = Reservation.new(params.require(:reservation).permit(:date_time, :party_size, :name))

		@reservation.save
		redirect_to @reservation
	end
	def index
		@reservations = Reservation.all
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name='viewport', content='width=device-width, initial-scale=1.0'/>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'%>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css'%>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>RailsRestaraunt</title>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">R-R</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/reservations/new">Create Reservation</a></li>
        <li><a href="/reservations">View Reservations</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/reservations/index.html.erb
<h1>All Reservations</h1>
 
<table class="table">
  <tr>
    <th>Name</th>
    <th>Party Size</th>
    <th>Date</th>
  </tr>
 
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.name %></td>
      <td><%= reservation.party_size %></td>
      <td><%= reservation.date_time %></td>
    </tr>
  <% end %>
</table>

app/views/reservations/new.html.erb
<div class="well">
<%= bootstrap_form_for :reservation, url: reservations_path  do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :party_size %>
  <%= f.datetime_select :date_time %>
  <%= f.submit "Request Reservation" %>
<% end %>
</div>

app/views/reservations/show.html.erb
<h1>New Reservation Confirmed</h1>

<div class="well"/>
<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>
<p>
  <strong>Party Size:</strong>
  <%= @reservation.party_size %>
</p>
<p>
  <strong>Time:</strong>
  <%= @reservation.date_time %>
</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h1 class="banner"> Welcome to Rails Restaraunt </h1>
</div>